from __future__ import annotations

from tara.state.schema import ConversationPhase


def state_purpose(state: dict) -> dict:
    """Update phase to purpose statement. The actual response was already
    generated by central_intelligence."""
    return {
        "conversation_phase": ConversationPhase.PURPOSE_STATEMENT,
    }
