from __future__ import annotations

from tara.state.schema import ConversationPhase


def state_purpose(state: dict) -> dict:
    """Update phase to purpose statement and record in tactical memory.
    The actual response was already generated by central_intelligence."""
    return {
        "conversation_phase": ConversationPhase.PURPOSE_STATEMENT,
        "tactical_memory": {"consequences_used": ["amount_stated"]},
    }
